version: "3"
services:
  reverse-proxy:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - 80:80
    depends_on:
      - postgres
    volumes:
      - ./packages/config/nginx.conf:/etc/nginx/nginx.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"
  postgres:
    image: postgres:15.1
    networks:
      - linkbee_default
    volumes:
      - ./data/postgres:/data/postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=linkbee
    ports:
      - '5433:5432'
  mongo:
    image: mongo
    networks:
      - linkbee_default
    volumes:
      - ./data/mongo:/data/mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=linkbee
    ports:
      - '27017:27017'
    
  linkbee-api:
    build:
      context: ./apps/api
      target: builder
    command: npm run start:dev
    volumes:
      - ./src:/user/src/app/src
    image: linkbee-api
    env_file:
      - apps/api/.env.local
    ports:
      - "4000:4000"
      - "9229:9229"
    depends_on:
      - postgres
      - mongo
    networks:
      -  linkbee_default

networks:
  linkbee_default:
    driver: bridge