version: "3"
services:
  postgres:
    image: postgres:15.1
    networks:
      - backend_linkbee_default
    volumes:
      - ./data/postgres:/data/postgres
    env_file:
      - docker.env
    ports:
      - '5433:5432'
  
  mongo:
    image: mongo
    networks:
      - backend_linkbee_default
    volumes:
      - ./data/mongo:/data/mongo
    env_file:
      - docker.env
    ports:
      - '27017:27017'
    
  linkbee-be:
    build:
      context: .
    image: linkbee-be
    env_file:
      - .env.local
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - mongo
    networks:
      -  backend_linkbee_default

networks:
  backend_linkbee_default:
    driver: bridge