version: "3.8"
services:
  reverse-proxy:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - 80:80
    depends_on:
      - postgres
      - mongo
    volumes:
      - ./packages/config/nginx.conf:/etc/nginx/nginx.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"
  postgres:
    image: postgres:15.1
    networks:
      - linkbee_default
    volumes:
      - ./data/postgres:/data/postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=linkbee
    ports:
      - '5433:5432'

  mongo:
    image: mongo
    networks:
      - linkbee_default
    volumes:
      - ./data/mongo:/data/mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=linkbee
    ports:
      - '27017:27017'

networks:
  linkbee_default:
    driver: bridge